### ISSUE TITLE
How do I save/restore model?

### ISSUE THREAD

**Issue by dekdekbaloo** [jfkirk/tensorrec#8]
Hello, I'm pretty new to using both python and tensorflow.

From my basic understanding, there should be a way to serialize the trained model and bring it back to train more later.

As I read through tf's session doc, that might be a way to do it. However, I've looked through `session_management.py` but got no vision of how to achieve this.

Is this possible already? Or, maybe, I missed something?

**Comment by jfkirk** [comment]
Hey @dekdekbaloo ! Thanks for checking it out.

`TensorRec` doesn't have any convenience methods for saving and loading models yet -- personally, all my applications of it have been persistent in-memory.

Assigning myself to this ticket to build some convenience methods.

**Comment by Composmentis** [comment]
Cool and thanks for the response @jfkirk .. Even I tried the same as explained by @dekdekbaloo but was clueless that's why opened it as in issue. Looking forward to knowing how have you handled it.  But it would be helpful elaboration about your thought on this as we can also contribute to the final solution.

**Comment by jfkirk** [comment]
Great! Once I have a PR up, I'll tag you so you can take a look at how I tackle it and for any feedback you may have.

**Comment by jfkirk** [comment]
PR for saver/loader methods: https://github.com/jfkirk/tensorrec/pull/13

**Comment by jfkirk** [comment]
The PR has been merged so I'm closing this issue or now.
